// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {bridge} from '../models';
import {main} from '../models';

export function Activity():Promise<Array<bridge.Activity>>;

export function AllowOrigin(arg1:string):Promise<main.State>;

export function ClearActivity():Promise<void>;

export function CopyToken():Promise<void>;

export function DenyOrigin(arg1:string):Promise<main.State>;

export function Providers(arg1:boolean):Promise<Array<bridge.ProviderInfo>>;

export function RotateToken():Promise<main.State>;

export function Start():Promise<main.State>;

export function State():Promise<main.State>;

export function Stop():Promise<main.State>;
