// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Activity() {
  return window['go']['main']['App']['Activity']();
}

export function AllowOrigin(arg1) {
  return window['go']['main']['App']['AllowOrigin'](arg1);
}

export function ClearActivity() {
  return window['go']['main']['App']['ClearActivity']();
}

export function CopyToken() {
  return window['go']['main']['App']['CopyToken']();
}

export function DenyOrigin(arg1) {
  return window['go']['main']['App']['DenyOrigin'](arg1);
}

export function Providers(arg1) {
  return window['go']['main']['App']['Providers'](arg1);
}

export function RotateToken() {
  return window['go']['main']['App']['RotateToken']();
}

export function Start() {
  return window['go']['main']['App']['Start']();
}

export function State() {
  return window['go']['main']['App']['State']();
}

export function Stop() {
  return window['go']['main']['App']['Stop']();
}
